// Generated by gencpp from file package_1/Custom.msg
// DO NOT EDIT!


#ifndef PACKAGE_1_MESSAGE_CUSTOM_H
#define PACKAGE_1_MESSAGE_CUSTOM_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Point.h>

namespace package_1
{
template <class ContainerAllocator>
struct Custom_
{
  typedef Custom_<ContainerAllocator> Type;

  Custom_()
    : header()
    , message()
    , coordinate()  {
    }
  Custom_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , message(_alloc)
    , coordinate(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _coordinate_type;
  _coordinate_type coordinate;





  typedef boost::shared_ptr< ::package_1::Custom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package_1::Custom_<ContainerAllocator> const> ConstPtr;

}; // struct Custom_

typedef ::package_1::Custom_<std::allocator<void> > Custom;

typedef boost::shared_ptr< ::package_1::Custom > CustomPtr;
typedef boost::shared_ptr< ::package_1::Custom const> CustomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package_1::Custom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package_1::Custom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::package_1::Custom_<ContainerAllocator1> & lhs, const ::package_1::Custom_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.message == rhs.message &&
    lhs.coordinate == rhs.coordinate;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::package_1::Custom_<ContainerAllocator1> & lhs, const ::package_1::Custom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace package_1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::package_1::Custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package_1::Custom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_1::Custom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package_1::Custom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_1::Custom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package_1::Custom_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package_1::Custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "df4cbcc180f9e5f7082067ab54c916f7";
  }

  static const char* value(const ::package_1::Custom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdf4cbcc180f9e5f7ULL;
  static const uint64_t static_value2 = 0x082067ab54c916f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::package_1::Custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package_1/Custom";
  }

  static const char* value(const ::package_1::Custom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package_1::Custom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"string message\n"
"geometry_msgs/Point coordinate\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::package_1::Custom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package_1::Custom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.message);
      stream.next(m.coordinate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Custom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package_1::Custom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package_1::Custom_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "coordinate: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.coordinate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE_1_MESSAGE_CUSTOM_H
